### ISSUE TITLE
Write errors to stderr instead of stdout

### ISSUE THREAD

**Issue by m417z** [hfiref0x/SXSEXP#12]
I'd prefer to have only errors printed.

Another option is to add a verbosity flag, but writing errors to stderr is a common practice, and is probably easier to implement.

**Comment by hfiref0x** [comment]
Hello, check the following commit  https://github.com/hfiref0x/SXSEXP/commit/86afb0b2181e8f3bf61ced1f6a7b402f9a693333

**Comment by m417z** [comment]
Great, thanks! Missed these:
https://github.com/hfiref0x/SXSEXP/blob/86afb0b2181e8f3bf61ced1f6a7b402f9a693333/Source/sxsexp/main.c#L80
https://github.com/hfiref0x/SXSEXP/blob/86afb0b2181e8f3bf61ced1f6a7b402f9a693333/Source/sxsexp/main.c#L103
https://github.com/hfiref0x/SXSEXP/blob/86afb0b2181e8f3bf61ced1f6a7b402f9a693333/Source/sxsexp/main.c#L471
https://github.com/hfiref0x/SXSEXP/blob/86afb0b2181e8f3bf61ced1f6a7b402f9a693333/Source/sxsexp/main.c#L559-L560

**Comment by hfiref0x** [comment]
Thanks, added in https://github.com/hfiref0x/SXSEXP/commit/9a6dfc5bf94241e3834fd92c394f292f96304fe6
