### ISSUE TITLE
Error message when running

### ISSUE THREAD

**Issue by elhoim** [hfiref0x/SXSEXP#4]
`sxsexp32.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.`

Same message with sxsexp64.exe on stock Win10 1909 (64 bits).

Also tried using the compatibility mode option to Windows 8 and Windows 7, but with not sucess.

**Comment by hfiref0x** [comment]
![VirtualBox_win10test_20_05_2020_17_55_35](https://user-images.githubusercontent.com/10708977/82438381-29def800-9ac3-11ea-826b-eb24c887facd.png)
![VirtualBox_win10test_20_05_2020_17_58_02](https://user-images.githubusercontent.com/10708977/82438606-87734480-9ac3-11ea-9e74-65b6465ba7c5.png)
